### PR TITLE
build with interviews

### PR DESCRIPTION
**Pull request by minrk**
This seems to work.

I initially thought we wanted `-DIV_ENABLE_X11_DYNAMIC=ON` to make X optional, but ran into:

1. it doesn't seem to work on mac (it doesn't find xquartz at runtime, despite building successfully), and
2. bundling X dependencies doesn't seem to be a problem, since they ship as regular conda dependencies, and neuron works fine without X when X is unavailable

closes #21

### CODE REVIEW

**Comment by minrk** [comment]
@espenhgn can you test / comment on this? It seems to resolve everything in #21

**Comment by espenhgn** [comment]
> @espenhgn can you test / comment on this? It seems to resolve everything in #21

Sure can do!

**Comment by espenhgn** [comment]
Hi @minrk; 
I think these builds may be affected by the odd Xcode install path as I posted about in #24 here: https://github.com/conda-forge/neuron-feedstock/pull/24#issuecomment-801231869

There are many references like `"CONDA_BUILD_SYSROOT": "/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk",` throughout the build logs like in this one https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/291478/logs/133

However, some of the older builds I know to be working does similar (https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/180626/logs/102) by setting `CONDA_BUILD_SYSROOT` to `/Applications/Xcode_11.3.1.app/...` so I'm frankly unsure why this is now a problem. I wouldn't think the bump in c-/cxx-compiler version from 9 to 11 would matter for instance.

Other than that the build recipe/logs look sane; Interviews appears to be found by cmake etc. I would've liked to test the builds locally prior to merging, but it doesn't look like any build artifacts have been stored anywhere (don't think that was ever the case). 

I have both my old macbook as well as a new M1 equipped mac at my disposal and would not mind testing on both machines. Somewhat surprisingly, the old 7.7.2 builds runs without issues (as far as I can tell) on the new machine with Rosetta. What I can do is try and replicate the build environment etc locally and step through the build recipe manually and see how that goes. 

I did some testing on a linux VM as well with the current version 7.8.2 on conda-forge; there everything seems fine. As not much changed in this PR I don't expect any issues occurring due to the inclusion of Interviews in this PR either.

**Comment by espenhgn** [comment]
Hi again. Looked a bit more into this and in Neuron's main CMakeLists.txt file if Readline is found then cmake is instructed to find packages Curses and Termcap quietly in that order, and would locate and link Curses provided by Xcode. The readline libraries provided by conda-forge depends on libncurses which is anyway installed with readline. The file `cmake/modules/FindReadline.cmake makes several references to Ncurses, so I don't understand why Curses appears to be preferred elsewhere. 

I did try and remove the lines 
```
  find_package(Curses QUIET)
  find_package(Termcap QUIET)
```
from CMakeLists.txt and could still compile Neuron with Interviews based on the procedure in build.sh from this PR. I can also compile mod files with this build. 

Perhaps the way to proceed would be to patch CMakeLists.txt to skip checking for Curses and Termcap while configuring the builds? These package lookups may be redundant.

**Comment by pramodk** [comment]
If I can jump in here:

> The readline libraries provided by conda-forge depends on libncurses which is anyway installed with readline. 

As you indicated above, readline is not necessarily shipped with nurses and hence we look for curses explicitly.

> I can also compile mod files with this build.

Along with this, if you launch neurondemo and if it opens GUI then I believe everything should be good!

image

**Comment by espenhgn** [comment]
> If I can jump in here:
> 
> > The readline libraries provided by conda-forge depends on libncurses which is anyway installed with readline.
> 
> As you indicated above, readline is not necessarily shipped with nurses and hence we look for curses explicitly.

Thanks. I think for these conda-forge builds searching for curses is redundant as ncurses is installed with readline in the build environment.
Right now ncurses is not explicitly listed as a build dependency in the meta.yaml file, but it could be (in case something would change with readline from conda-forge in the future). 
I opened a PR to @minrk's fork/this PR here https://github.com/minrk/neuron-feedstock/pull/1 patching the CMakeLists.txt file but I think he must decide himself to accept it. 

> 
> > I can also compile mod files with this build.
> 
> Along with this, if you launch neurondemo and if it opens GUI then I believe everything should be good!
> 
> image

Yes, the GUI worked on my end.

**Comment by minrk** [comment]
> Right now ncurses is not explicitly listed as a build dependency in the meta.yaml file,

ncurses is already in meta.yaml in the host dependencies, as it should be if it's linked directly.

My guess is that FindCurses finds `libcurses`, which is in the SDK before it tries to find `libncurses`, which is in the host env.

I added `-DCURSES_NEED_NCURSES=ON`, which seems to find ncurses first, and no longer reports any links to the SDK, so I don't think we need to patch the cmake files.

Unfortunately, it's really hard to test if it's truly going to work fully without making and publishing a release.

I was able to run the build on my mac and it succeeded with both IV_X11_DYNAMIC on and off. Ideally, it would be on, but when I turned it on it never loaded X11 on my mac int he same environment where the non-dynamic X11 worked just fine. So I'm inclined to leave the dynamic X11 off, since it does *work*, it just outputs a warning on startup.

Then we can explore the dynamic X11 at a later time (or maybe enable it just on linux?).

What are your perspectives on dynamic X11? Is the main reason because X *libraries* might be unavailable? Because that can't happen with conda - the X libs are an explicit dependency, so will always be present. If there's no big downside to X display being unavailable, then the simpler direct linking probably makes the most sense.

**Comment by espenhgn** [comment]
Hi @minrk; I tried recompiling with the added `-DCURSES_NEED_NCURSES=ON` flag, and this fixes the issue with Xcode/libcurses indeed. I'll close the PR I created then!
I do see one failing test in the python neuron module. This is not occurring on Azure and I assume it is due to something on my config and can be ignored:
```
python -c "import neuron; neuron.test()" 
....
testRxDexistence (neuron.tests.test_neuron.NeuronTestCase) ... has_geometry3d is False
Traceback (most recent call last):
  File "/Users/ehagen/anaconda3/envs/neuron/lib/python3.9/site-packages/neuron/rxd/rxd.py", line 1463, in _init
    initializer._do_init()
  File "/Users/ehagen/anaconda3/envs/neuron/lib/python3.9/site-packages/neuron/rxd/initializer.py", line 26, in _do_init
    obj._do_init()
  File "/Users/ehagen/anaconda3/envs/neuron/lib/python3.9/site-packages/neuron/rxd/region.py", line 358, in _do_init
    raise RxDException('selected geometry (%r) does not support 3d mode' % self._geometry)
neuron.rxd.rxdException.RxDException: selected geometry (<neuron.rxd.geometry.RxDGeometry object at 0x106ca5610>) does not support 3d mode
NEURON: Python Callback failed
 near line 0
 objref hoc_obj_[2]
                   ^
        finitialize(-65)
'basicRxD3D()' failed hoc error
Process Process-2:
Traceback (most recent call last):
  File "/Users/ehagen/anaconda3/envs/neuron/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/ehagen/anaconda3/envs/neuron/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ehagen/anaconda3/envs/neuron/lib/python3.9/site-packages/neuron/tests/test_neuron.py", line 148, in RxDexistence
    assert(error == 0)
AssertionError
FAIL
testSectionListIterator (neuron.tests.test_neuron.NeuronTestCase)
As of v8.0, iteration over a SectionList does not change the cas ... ok
testpsection (neuron.tests.test_neuron.NeuronTestCase) ... ok

======================================================================
FAIL: testRxDexistence (neuron.tests.test_neuron.NeuronTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ehagen/anaconda3/envs/neuron/lib/python3.9/site-packages/neuron/tests/test_neuron.py", line 168, in testRxDexistence
    assert(p.exitcode == 0)
AssertionError

----------------------------------------------------------------------
Ran 12 tests in 2.703s

FAILED (failures=1)
```
I think this PR can be soon merged then as it should take care of the immediate issue of currently broken osx builds on the  conda-forge.

**Comment by minrk** [comment]
OK, thanks!

**Comment by espenhgn** [comment]
Thanks for merging! Checked all 3.9 builds on my older macbook, M1 equipped macbook and an ubuntu VM. *Everything* 
(`import neuron; neuron.test()`; `neurondemo`) seems to be working. Also LFPy-2.2 from conda-forge ran all tests successfully with the MPI-enabled neuron variants.

**Comment by pramodk** [comment]
thank you @minrk and @espenhgn from neuron-dev team! Hopefully we will build some expertise on conda and able to contribute proactively.

**Pull request merged**
