### PR TITLE
Updates NEURON to v7.8.1.1 using official wheels from PyPI

### PR DESCRIPTION
**Pull request by espenhgn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR provides builds with the official NEURON-7.8.1.1 wheel files on Linux and OSX platforms from https://pypi.org/project/NEURON/. 
Python 3.6, 3.7 and 3.8 is supported. Python 3.9 support should be straight-forward to add as soon as corresponding wheels are provided (an issue has been raised at https://github.com/neuronsimulator/nrn/issues/815)

- In contrast to the older crippled builds both the GUI and reaction-diffusion (`rx3d`) module are provided
- Removed the `nompi`, `openmpi` and `mpich` variants. Users and packages that depend on NEURON and require MPI can install OpenMPI or MPICH from conda-forge if needed. 
- the MPI test script is executed with `openmpi` only - I would add checks with `mpich` as well, but didn't find a way to create multiple test environments without creating different MPI variants
- ideally, one would compile NEURON and Interviews from source, which now should be made "simpler" with cmake, but I had no success in incorporating all X11 dependencies using libraries from conda-forge/host image. 
- Windows is not yet officially supported via pip install.

### CODE REVIEW

**Comment by espenhgn** [comment]
@minrk , please let me know if you are ok with wrapping the official Neuron wheels from PyPI instead of providing a partial build. If you are fine with this solution, then I think this PR could be merged.

**Comment by minrk** [comment]
Sorry, I haven't had time to look at this in a while. In general, conda-forge should build packages from source and properly link (never bundle) dependencies as shared (ideally not static) libraries and not re-bundle binaries.

For the issues/missing features in the package, we should be able to follow the example of the new [upstream CI builds](https://github.com/neuronsimulator/nrn/blob/master/azure-pipelines.yml) and match everything appropriately.

**Comment by espenhgn** [comment]
I fully agree with the sentiment that packages should preferably be built using dependencies already provided by conda-forge or default build image. I just gave up on it around this point in this closed PR: https://github.com/conda-forge/neuron-feedstock/pull/19/commits/e32fa448f0f89a18159c72e38eff43412321c805 - there was a compiling issue similar to `glibc_2.14' not found` that I couldn't resolve (for linux).

Perhaps some of the active neuron developers (calling @pramodk, @alexsavulescu) could be persuaded to look into a proper conda build. I have no time or incentive really. For my purposes (mainly LFPy), I haven't encountered any issues by pip-installing neuron in different environments on macos or linux.

**Comment by minrk** [comment]
I also initially packaged neuron for my own purposes, which is mainly LFPy in a docker image for a summer school course, which means it's hugely beneficial to *not* require GUI dependencies, since I ~always use it in a context where no display will be available anyway. Having GUI-enabled builds as well is certainly something we should do; that's just why it started where it is (dealing with X dependencies in a portable way is also just harder than not doing it!)

I will try to find some time to update the recipe based on the upstream CI builds, perhaps over the coming holiday.

**Comment by pramodk** [comment]
Thank you very much for this work @espenhgn and @minrk and notifying us. We don't have too much experience with conda packaging but will come back here after going through this PR. cc: @alexsavulescu @nrnhines @ferdonline @ohm314

**Comment by minrk** [comment]
I have a bit of time to put into this, and hope to get everything up-to-date this week (#24 is the start)

After it's up-to-date again, we can look at adding interviews builds for linux.

Some advice from upstream would be super helpful. With the various components, ideally we would build each one separately and link dependencies. I.e. build and install neuron *without* Python, then *only* build the Python bindings. that will be vastly more efficient for targeting multiple Python versions, since neuron itself will only be built once per platform.

But the build system doesn't seem set up that way in clearly separated stages, so that's harder.

**Comment by pramodk** [comment]
Hello @minrk : 

> Some advice from upstream would be super helpful. With the various components, ideally we would build each one separately and link dependencies. I.e. build and install neuron without Python, then only build the Python bindings. that will be vastly more efficient for targeting multiple Python versions, since neuron itself will only be built once per platform.

Happy to help from our side. (cc: @olupton @alexsavulescu)

As you mentioned, currently there is no support for building python bindings separately. I don't that will be easy / straightforward in current setup. But what we have done is support to do single build with multiple pythons. For example, one can use `-DNRN_ENABLE_PYTHON_DYNAMIC=ON` and `-DNRN_PYTHON_DYNAMIC="/path/python3.6;/path/python3.7;/path/python3.8;"`:

```bash
cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/install \
-DNRN_ENABLE_CORENEURON=OFF \
-DNRN_ENABLE_INTERVIEWS=OFF \
-DNRN_ENABLE_PYTHON_DYNAMIC=ON \
-DNRN_PYTHON_DYNAMIC="/usr/bin/python3;/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/python-3.7.4-tfxecymrkn/bin/python;/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/python-3.8.3-suxrst/bin/python"
...

-- MPI           | ON
--   INC         | /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/hpe-mpi-2.22.hmpt-r52ypu/include
--   LIB         | /lib64/libpthread.so
--   DYNAMIC     | OFF
-- Python        | ON
--   EXE         | /usr/bin/python3
--   INC         | /usr/include/python3.4m
--   LIB         | /usr/lib64/libpython3.4m.so.1.0
--   MODULE      | ON
--   DYNAMIC     | ON
--     EXE       | /usr/bin/python3
--     INC       | /usr/include/python3.4m
--     LIB       | /usr/lib64/libpython3.4m.so.1.0
--     INSTALL C | /usr/bin/python3 setup.py install --prefix= --home=/gpfs/bbp.cscs.ch/home/kumbhar/tmp/nrn/build/install
--     EXE       | /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/python-3.7.4-tfxecymrkn/bin/python
--     INC       | /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/python-3.7.4-tfxecymrkn/include/python3.7m
--     LIB       | /usr/lib64/libpython3.4m.so.1.0
--     INSTALL C | /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/external-libraries/2020-02-01/linux-rhel7-x86_64/gcc-8.3.0/python-3.7.4-tfxecymrkn/bin/python setup.py install --prefix= --home=/gpfs/bbp.cscs.ch/home/kumbhar/tmp/nrn/build/install
--     EXE       | /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/python-3.8.3-suxrst/bin/python
--     INC       | /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/python-3.8.3-suxrst/include/python3.8
--     LIB       | /usr/lib64/libpython3.4m.so.1.0
--     INSTALL C | /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/python-3.8.3-suxrst/bin/python setup.py install --prefix= --home=/gpfs/bbp.cscs.ch/home/kumbhar/tmp/nrn/build/install
-- Readline      | /usr/lib64/libreadline.so
```

I just realised that we haven't documented this option and probably not testing enough but this was added precisely to avoid multiple installations with different pythons.

**Comment by minrk** [comment]
Updated to 7.8.2 in #24 

@pramodk thanks for the info! The dynamic Python is cool, and indeed was required to get a working build on mac even with just one Python (not sure what's up there but could be related to static/dynamic linking of Python itself in conda-forge).

Unfortunately, targeting multiple Pythons in one build doesn't work for us here because we can't make more than one Python available at build time.

**Comment by espenhgn** [comment]
Closing this as 7.8.2 is now available via #24

**Pull request closed without merging**
