### PR TITLE
adds C compiler as run time dependency for MPI builds

### LINKED ISSUE #16: Open MPI wrapper compiler unable to find specified compiler in PATH
Issue:
Users of NEURON more often than not will need to compile NMODL (`.mod`) language files required by their model(s), using the `nrnivmodl` script. That doesn't work with the current MPI builds in a minimal environment with `neuron`. I demonstrate this here on OSX but the issue exist on linux as well. The issue exist for both `openmpi` and `mpich` variants:

```
$ conda create -n neuron neuron=*=mpi* --yes
$ conda activate neuron
$ nrnivmodl
Creating x86_64 directory for .o files.

/Users/ehagen/Repositories/neuron-feedstock-test
expsyni.mod
expsyni.mod
"/Users/ehagen/anaconda3/envs/neuron/bin/nocmodl" expsyni
"/Users/ehagen/anaconda3/envs/neuron/share/nrn/libtool" --tag=CC --mode=compile mpicc -DHAVE_CONFIG_H  -I. -I.. -I"/Users/ehagen/anaconda3/envs/neuron/include/nrn" -I"/Users/ehagen/anaconda3/envs/neuron/lib"      -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/ehagen/anaconda3/envs/neuron/include -fdebug-prefix-map=/usr/local/miniconda/conda-bld/neuron_1579771171236/work=/usr/local/src/conda/neuron-7.7.2 -fdebug-prefix-map=/Users/ehagen/anaconda3/envs/neuron=/usr/local/src/conda-prefix -c -o mod_func.lo mod_func.c
Translating expsyni.mod into expsyni.c
Thread Safe
"/Users/ehagen/anaconda3/envs/neuron/share/nrn/libtool" --tag=CC --mode=compile mpicc -DHAVE_CONFIG_H  -I. -I.. -I"/Users/ehagen/anaconda3/envs/neuron/include/nrn" -I"/Users/ehagen/anaconda3/envs/neuron/lib"      -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/ehagen/anaconda3/envs/neuron/include -fdebug-prefix-map=/usr/local/miniconda/conda-bld/neuron_1579771171236/work=/usr/local/src/conda/neuron-7.7.2 -fdebug-prefix-map=/Users/ehagen/anaconda3/envs/neuron=/usr/local/src/conda-prefix -c -o expsyni.lo expsyni.c
libtool: compile:  mpicc -DHAVE_CONFIG_H -I. -I.. -I/Users/ehagen/anaconda3/envs/neuron/include/nrn -I/Users/ehagen/anaconda3/envs/neuron/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem /Users/ehagen/anaconda3/envs/neuron/include -fdebug-prefix-map=/usr/local/miniconda/conda-bld/neuron_1579771171236/work=/usr/local/src/conda/neuron-7.7.2 -fdebug-prefix-map=/Users/ehagen/anaconda3/envs/neuron=/usr/local/src/conda-prefix -c mod_func.c  -fno-common -DPIC -o .libs/mod_func.o
--------------------------------------------------------------------------
The Open MPI wrapper compiler was unable to find the specified compiler
x86_64-apple-darwin13.4.0-clang in your PATH.

Note that this compiler was either specified at configure time or in
one of several possible environment variables.
--------------------------------------------------------------------------
make: *** [mod_func.lo] Error 1
make: *** Waiting for unfinished jobs....
libtool: compile:  mpicc -DHAVE_CONFIG_H -I. -I.. -I/Users/ehagen/anaconda3/envs/neuron/include/nrn -I/Users/ehagen/anaconda3/envs/neuron/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem /Users/ehagen/anaconda3/envs/neuron/include -fdebug-prefix-map=/usr/local/miniconda/conda-bld/neuron_1579771171236/work=/usr/local/src/conda/neuron-7.7.2 -fdebug-prefix-map=/Users/ehagen/anaconda3/envs/neuron=/usr/local/src/conda-prefix -c expsyni.c  -fno-common -DPIC -o .libs/expsyni.o
--------------------------------------------------------------------------
The Open MPI wrapper compiler was unable to find the specified compiler
x86_64-apple-darwin13.4.0-clang in your PATH.

Note that this compiler was either specified at configure time or in
one of several possible environment variables.
--------------------------------------------------------------------------
make: *** [expsyni.lo] Error 1
```
where `expsyni.mod` is (sorry for file length):
```
TITLE Exponential-function synaptic current, with NET_RECEIVE

COMMENT
This model works with variable time-step methods (although it may not
be very accurate) but at the expense of having to maintain the queues
of spike times and weights.
Andrew P. Davison, UNIC, CNRS, May 2006

Note: converted to Exponential current kernel. 

ENDCOMMENT

DEFINE MAX_SPIKES 1000
DEFINE CUTOFF 20

NEURON {
	POINT_PROCESS ExpSynI
	RANGE tau, i, q
	NONSPECIFIC_CURRENT i
}

UNITS {
	(nA) = (nanoamp)
}

PARAMETER {
	tau = 5 (ms) <1e-9,1e9>

}

ASSIGNED {
	i (nA)
	q
	onset_times[MAX_SPIKES] (ms)
	weight_list[MAX_SPIKES] (nA)
}

INITIAL {
	i  = 0
	q  = 0 : queue index
}

BREAKPOINT {
	LOCAL k, expired_spikes, x
	i = 0
	expired_spikes = 0
	FROM k=0 TO q-1 {
		x = (t - onset_times[k])/tau
		if (x > CUTOFF) {
			expired_spikes = expired_spikes + 1
		} else {
			i = i - weight_list[k] * exp_current(x)
		}
	}
	update_queue(expired_spikes)
}

FUNCTION update_queue(n) {
	LOCAL k
	:if (n > 0) { printf("Queue changed. t = %4.2f onset_times=[",t) }
	FROM k=0 TO q-n-1 {
		onset_times[k] = onset_times[k+n]
		weight_list[k] = weight_list[k+n]
		:if (n > 0) { printf("%4.2f ",onset_times[k]) }
	}
	:if (n > 0) { printf("]\n") }
	q = q-n
}

FUNCTION exp_current(x) {
	if (x < 0) {
		exp_current = 0
	} else {
		exp_current = exp(-x)
	}
}

NET_RECEIVE(weight (nA)) {
	onset_times[q] = t
	weight_list[q] = weight
	if (q >= MAX_SPIKES-1) {
		printf("Error in ExpSynI. Spike queue is full\n")
	} else {
		q = q + 1
	}
}
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/ehagen/anaconda3/envs/neuron:
#
# Name                    Version                   Build  Channel
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcxx                    10.0.0               h1af66ff_2    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgfortran               4.0.0                         2    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10               h3d69b6c_0    conda-forge
llvm-openmp               10.0.0               h28b9765_0    conda-forge
mpi                       1.0                     openmpi    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
neuron                    7.7.2           mpi_openmpi_py38haa1005d_0    conda-forge
numpy                     1.18.5           py38h1f821a2_0    conda-forge
openmpi                   4.0.4                hed52333_0    conda-forge
openssl                   1.1.1g               h0b31af3_0    conda-forge
pip                       20.1.1                     py_1    conda-forge
python                    3.8.3           cpython_hd5f0129_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
setuptools                47.3.1           py38h32f6830_0    conda-forge
sqlite                    3.32.3               h93121df_0    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h0b31af3_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : neuron
    active env location : /Users/ehagen/anaconda3/envs/neuron
            shell level : 1
       user config file : /Users/ehagen/.condarc
 populated config files : /Users/ehagen/.condarc
          conda version : 4.8.3
    conda-build version : 3.19.1
         python version : 3.7.6.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/ehagen/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/ehagen/anaconda3/pkgs
                          /Users/ehagen/.conda/pkgs
       envs directories : /Users/ehagen/anaconda3/envs
                          /Users/ehagen/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 505:20
             netrc file : None
           offline mode : False

```
</details>

### PR DESCRIPTION
**Pull request by espenhgn**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #16

The MPI-enabled C compiler should be a run-time (end-user) dependency for MPI builds, otherwise NMODL (.mod) language files cannot be compiled.

### CODE REVIEW

**Comment by espenhgn** [comment]
@conda-forge-admin, please rerender

**Comment by espenhgn** [comment]
built `linux_mpiopenmpipython3.8.____cpython` locally with success, but build times are very long.

**Comment by espenhgn** [comment]
@minrk, things appear to be working now. The re-render auto removed the py2.7 builds which I believe is fine.

**Comment by minrk** [comment]
Thanks!

**Pull request merged**
